railsapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'table' => 'table#show'
  get '/runner', to: 'table#runner'
end

railsapp/app/controllers/table_controller.rb
class TableController < ActionController::Base
  def show
    @start_time = Time.now
    # test = PdfGenerate.new
    # puts test.run
    @end_time = Time.now
    @process_time = @end_time - @start_time
  end

  def runner
    # PdfGenerateJob.perform_later
    @starting = Time.now
    pdf = PdfGenerateTest.new.render
    send_data pdf,
    #       filename:    'test_pdf.pdf',
          type:        'application/pdf',
          disposition: 'inline' # 画面に表示
    # redirect_to table_path
    @ending = Time.now
    logger.debug("-----#{@ending-@starting}")
  end
end

railsapp/app/views/table/show.html.erb
<p>Invoice format table test
  <br> Start time: <%= @start_time %>
  <br> End time: <%= @end_time %>
  <br> <%= $pages %> page pdf publish process time (sec): <%= @process_time %></p>

<div class="btn btn-primary">
  <%= link_to "Generate pdf",runner_path, download: "test-pdf", class: 'btn', id:"my_btn"%>
</div>

<%if File.exist?("#{Rails.root}/app/assets/pdf/explicit.pdf")%>
  <% path = asset_path("explicit.pdf")%>
<%end%>

<div id="pdf">
  <a href=<%path%>> My PDF</a>
</div>

<div id="loading">
  <p> Please Wait</p>
</div>


<script>
var $loading = $('#loading').hide();
var $pdf = $('#pdf').hide();

$("#my_btn").click(function(e){

   $.ajax({
        type: "GET",
        url: "/runner",
        beforeSend: function () {
          $loading.show();
        },
        complete: function () {
          $loading.hide();
          $pdf.show();
        },
    }); 
    e.preventDefault();
});

</script>